DATASET:
  NAME: simple01
  PATH: ../datasets/simple01_eng_letters/data/   # Path to the dataset directory, contains npz files
  LABEL_KEY: label          # optional, key for labels in npz files
  PREPROCESSING:
    CROP_SIZE:              # optional, if not set, will use the full image size
    CROP_TYPE: 'center'     # Options: center, random, corner, smart, multi_crop
    CROP_POSITION: 'center' # For corner cropping: top_left, top_right, bottom_left, bottom_right, center
    AUGMENT: false          # Enable data augmentation (rotation, flip, etc.)
    AUGMENT_TYPE:           # fliplr, flipud, rotate90
    CLIP_MIN: -1.0
    CLIP_MAX: 1.0

TRAINING:
  IS_NEW_TRAIN: true
  TRAINED_H5:
  INPUT_IMAGE_SIZE: 64
  INPUT_IMAGE_CHANNEL: 1
  PRED_TYPE: 'velocity'
  LOSS_FN: MSE
  INLINE_GEN:
    ENABLE: true
    NUMS: 20
    PERIOD: 10  # Generate images every N epochs
    REVERSE_STRIDE: 10
  HYPER_PARAMETERS:
    EPOCHS: 100
    STEPS_PER_EPOCH: 100
    BATCH_SIZE: 8
    SAVE_PERIOD:      # Save model every N epochs
    LR_TYPE: constant    # Options: constant, warmup_cosine
    LEARNING_RATE: 0.0001
    WARMUP_STEPS:        # for warmup_cosine 
  NETWORK:
    BLOCK_SIZE: 1
    SCHEDULER: linear
    TIMESTEPS: 1000
    NUM_RES_BLOCKS: 2
    NORM_GROUPS: 8
    TIME_EMB_DIM: 128
    FIRST_CHANNEL: 16
    CHANNEL_MULTIPLIER: [1, 2, 4, 8]
    HAS_ATTENTION: [False, False, True, True]
    NUM_HEADS: 1
    DROPOUT_RATE: 0.1
    NUM_CLASSES: 26
  OUTPUT_DIR: "./training_outputs"

IMAGE_GENERATION:
  MODEL_PATH: 
  GEN_TASK: "random"  # Options: random_uncond, channel_inpaint
  NUM_GEN_IMAGES: 20
  EXTERNAL_NPZ_INPUT:
  CLASS_LABEL:
  FREEZE_CHANNEL:
  REVERSE_STRIDE: 10
  DDIM_ETA: 1.0
  EXPORT_INTERM: false
  GEN_SAVE_DIR:
  RANDOM_SEED:
