DATASET:
  NAME: simple01
  PATH: ../simple_npz_datasets/eng_letters_26x64x64x1.npz
  PREPROCESSING:
    CROP_SIZE:
    CLIP_MIN: -1.0
    CLIP_MAX: 1.0

TRAINING:
  IS_NEW_TRAIN: true
  TRAINED_H5:
  INPUT_IMAGE_SIZE: 64
  INPUT_IMAGE_CHANNEL: 1
  PRED_TYPE: 'velocity'
  LOSS_FN: MSE 
  HYPER_PARAMETERS:
    EPOCHS: 500
    LR_TYPE: constant
    STEPS_PER_EPOCH: 60
    BATCH_SIZE: 4
    LEARNING_RATE: 0.0001
    WARMUP_STEPS: 500
  NETWORK:
    BLOCK_SIZE: 1
    SCHEDULER: linear
    TIMESTEPS: 1000
    NUM_RES_BLOCKS: 2
    NORM_GROUPS: 16
    TIME_EMB_DIM: 64
    FIRST_CHANNEL: 16
    CHANNEL_MULTIPLIER: [1, 2, 4, 8]
    HAS_ATTENTION: [False, False, False, False]
    NUM_HEADS: 1
    DROPOUT_RATE: 0.1
    KERNEL_SIZE: 3
    USE_CROSS_ATTENTION: false
  OUTPUT_DIR: "./training_outputs"

IMAGE_GENERATION:
  MODEL_PATH: 
  NUM_GEN_IMAGES: 20
  EXPORT_INTERM: false
  REVERSE_STRIDE: 10
  DDIM_ETA: 1.0
  RANDOM_SEED:
  GEN_INPUTS:
  GEN_OUTPUT_DIR: gen_temp
