DATASET:
  NAME: cifar10
  PATH: null
  PREPROCESSING:
    CLIP_SIZE:
    CLIP_MIN: -1.0
    CLIP_MAX: 1.0

TRAINING:
  IS_NEW_TRAIN: true
  TRAINED_H5:
  INPUT_IMAGE_SIZE: 32
  INPUT_IMAGE_CHANNEL: 3
  PRED_TYPE: 'velocity'
  LOSS_FN: MSE
  HYPER_PARAMETERS:
    EPOCHS: 1000
    BATCH_SIZE: 64
    LEARNING_RATE: 0.0001
  NETWORK:
    TIMESTEPS: 1000
    SCHEDULER: 'cosine'
    NUM_RESNET_BLOCKS: 2
    NORM_GROUPS: 32
    FIRST_CHANNEL: 32
    CHANNEL_MULTIPLIER: [1, 2, 2, 2]
    HAS_ATTENTION: [False, True, False, False]
    BLOCK_SIZE: 1
  OUTPUT_DIR: "./training_outputs"

IMAGE_GENERATION:
  MODEL_PATH:
  NUM_GEN_IMAGES: 1000
  EXPORT_INTERM: false
  REVERSE_STRIDE: 10
  DDIM_ETA: 1.0
  RANDOM_SEED: 1234
  GEN_INPUTS:
  GEN_OUTPUT_DIR:
