DATASET:
  NAME: cifar10
  PATH: null
  PREPROCESSING:
    CLIP_SIZE:
    CLIP_MIN: -1.0
    CLIP_MAX: 1.0

TRAINING:
  IS_NEW_TRAIN: true
  TRAINED_H5:
  INPUT_IMAGE_SIZE: 32
  INPUT_IMAGE_CHANNEL: 3
  MODEL_PRED: 'noise'
  HYPER_PARAMETERS:
    EPOCHS: 5000
    BATCH_SIZE: 32
    LEARNING_RATE: 0.0001
  NETWORK:
    _EMA: 0.999
    SCHEDULER: linear
    TIMESTEPS: 1000
    NUM_RESNET_BLOCKS: 2
    NORM_GROUPS: 32
    FIRST_CHANNEL: 128
    CHANNEL_MULTIPLIER: [1, 2, 2, 2]
    HAS_ATTENTION: [False, True, False, False]
  OUTPUT_DIR: "./training_outputs"

IMAGE_GENERATION:
  MODEL_PATH:
  NUM_GEN_IMAGES: 1000
  EXPORT_INTERM: false
  REVERSE_STRIDE: 10
  GEN_METHOD: 'ddim'
  DDIM_ETA: 1.0
  RANDOM_SEED:
  GEN_INPUTS:
  GEN_OUTPUT_DIR:
