DATASET:
  NAME: cifar10
  PATH: null
  PREPROCESSING:
    CLIP_SIZE:
    CLIP_MIN: -1.0
    CLIP_MAX: 1.0

TRAINING:
  IS_NEW_TRAIN: new
  TRAINED_H5:
  INPUT_IMAGE_SIZE: 32
  INPUT_IMAGE_CHANNEL: 3
  HYPER_PARAMETERS:
    EPOCHS: 4000
    BATCH_SIZE: 32
    LEARNING_RATE: 0.0002
  NETWORK:
    SCHEDULER: linear
    TIMESTEPS: 1000
    NUM_RESNET_BLOCKS: 2
    NORM_GROUPS: 8
    FIRST_CHANNEL: 32
    CHANNEL_MULTIPLIER: [1, 2, 4, 8]
    HAS_ATTENTION: [False, False, True, True]
  OUTPUT_DIR: "./training_outputs"

IMAGE_GENERATION:
  MODEL_PATH:
  OUTPUT_IMAGE_SIZE: 32
  OUTPUT_IMAGE_CHANNEL: 3
  NUM_GEN_IMAGES: 100
  GIVEN_SAMPLES: 
  GEN_OUTPUT_DIR: "auto"
  EXPORT_INTERM: false
  PREV_N_STEP: 1
